apiVersion: v1
kind: Pod
metadata:
  name: spica
  namespace: infrastructure-spicaengine-com
  labels:
    app: spica
spec:
  containers:
    - name: site
      image: spicaengine/site
      imagePullPolicy: Always
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"
        limits:
          memory: "20Mi"
          cpu: "20m"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spica-svc
  namespace: infrastructure-spicaengine-com
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: spica
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spica-gateway
  namespace: infrastructure-spicaengine-com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts: [spicaengine.com]
      secretName: spicaengine
  rules:
    - host: spicaengine.com
      http:
        paths:
          - backend:
              serviceName: spica-svc
              servicePort: 80
