var_1: &docker_plugin
  plugins:
    - docker#v3.5.0:
        image: "spicaengine/buildkite-node-with-mongodb@sha256:f7cd5ed3576528833a3a47819ab28e38d915094fa1904c39b248f3ee2ff395ce"
        workdir: /spica
        volumes:
          - "/var/cache/spica:/var/cache/spica"
          - "/var/cache/spica/node_modules:/spica/node_modules"
          - "/var/cache/spica/docs/site/node_modules:/spica/docs/site/node_modules"
          - "./.buildkite/bazel.rc:/etc/bazel.bazelrc"
          # These are secrets, which shall not be exposed that are stored in the agent
          - "/root/website-service-account.json:/root/website-service-account.json"

steps:
  - label: ":yarn: Install packages"
    key: "install_packages"
    <<: *docker_plugin
    commands:
      - yarn config set cache-folder /var/cache/spica/.cache
      - yarn install --frozen-lockfile --network-timeout 1000000

  - label: ":plaidml: + :bazel: Builds Docs"
    key: generate_docs
    if: build.branch != "master"
    depends_on: "install_packages"
    <<: *docker_plugin
    commands:
      - yarn --silent bazelisk build //docs/content

  - label: ":angular: Production Build"
    key: build_prod
    if: build.branch != "master"
    depends_on:
      - install_packages
      - generate_docs
    <<: *docker_plugin
    commands:
      - cd docs/site && yarn ng build --prod --progress=false

  - label: ":firebase: Deployment"
    key: deployment
    if: build.branch == "master"
    depends_on:
      - install_packages
    <<: *docker_plugin
    commands:
      - yarn --silent bazelisk build //docs/content
      - cd docs/site && yarn ng build --prod --progress=false
      - export GOOGLE_APPLICATION_CREDENTIALS="/root/website-service-account.json"
      - yarn firebase deploy
